### ISSUE TITLE
Infinite error loop when root element is not found during `TyrianApp.launch`

### ISSUE THREAD

**Issue by grzegorz-bielski** [PurpleKingdomGames/tyrian#131]
Hi!

For starters I must say that Indigo & Tyrian are really cool projects, please keep it up!

Still, I experienced some issues...

Given this setup code:
```javascript
TyrianApp.launch("main");
```
When the element with id `main` is not found in the page Tyrian goes into following error loop:
<img width="713" alt="Screenshot 2022-08-14 at 10 08 21" src="https://user-images.githubusercontent.com/22674545/184528272-a36d6341-0b49-4273-b5cc-75a2c5062ab6.png">

I expect there should be some fail fast semantic during `launch`.

Additional snag: 
Could `launch` accept the DOM element in addition to `containerId`? 
I imagine not everyone wants to use `id`, or already have a reference to the DOM node and wants to use it instead.

**Comment by davesmith00000** [comment]
Hi!

Glad you're enjoying them!

That is a nasty looking bug, I've raised an [issue on Indigo too](https://github.com/PurpleKingdomGames/indigo/issues/400) to see if it also applies there since they work in a similar way.

> Could `launch` accept the DOM element in addition to `containerId`?

Definitely, we don't do it yet only because it isn't a use case I've needed. But all we have to do is refactor the `launch` functions a little to _not_ do [the `getElementByID` look up in the `ready` function](https://github.com/PurpleKingdomGames/tyrian/blob/main/tyrian/js/src/main/scala/tyrian/TyrianAppF.scala#L63), and also provide overrides that accept an `Element`, [as `start` does](https://github.com/PurpleKingdomGames/tyrian/blob/main/tyrian/js/src/main/scala/tyrian/Tyrian.scala#L45) alongside the existing ones.

**Comment by davesmith00000** [comment]
Thinking a little more about it, it may be worth rethinking the name of `launch` function to make it more clear which one you're calling from JS.

**Comment by davesmith00000** [comment]
Broken out the bit about calling launch with an element into it's own [issue](https://github.com/PurpleKingdomGames/tyrian/issues/135). (Makes the release notes easier to generate)

**Comment by davesmith00000** [comment]
Both issues fixed in [PR](https://github.com/PurpleKingdomGames/tyrian/issues/135).
