### ISSUE TITLE
Web Socket subscription drops initial messages

### ISSUE THREAD

**Issue by gvolpe** [PurpleKingdomGames/tyrian#149]
Hi @davesmith00000 👋🏽 

I've been debugging all day (going crazy really 😄) a subtle issue with the Web Socket subscriptions and I now have a lead, but unfortunately not a fix yet.

As far I can observe, once a connection is established, there seems to be a delay in registering the subscription and so messages that arrive immediately are never processed by Tyrian, but they can be seen in the browser's developer console.

![msg](https://i.imgur.com/8nOwYhx.png)

I think the last version where this was working as expected was 0.3.2, so shame on me, I haven't properly tested my application to find this issue sooner.

I tried to minimize the example using the Echo Server from the examples. For example, there is a [message](https://github.com/PurpleKingdomGames/tyrian/blob/main/examples/websocket/server/websocketserver.js#L11) saying "Connection made...", which doesn't get to Tyrian subs. 

Long shot, but do you recall if this message was being processed on versions 0.3.2 and lower?

On my application, I temporarily added a delay before sending the `Attached` message, but it's not a long-term solution.

------

Unrelated question: Is there a Matrix bridge for the Discord channel?

**Comment by davesmith00000** [comment]
> Unrelated question: Is there a Matrix bridge for the Discord channel?

Given I only vaguely know what the means the answer is almost certainly, no, but happy to look into it?

**Comment by davesmith00000** [comment]
WebSockets: Well that's a shame! Your description implies its been broken since we introduced Cats Effect / fs2. I will look into it - hopefully this evening - and report back.

**Comment by gvolpe** [comment]
RE: Matrix bridge, I don't have much experience in setting it up either, but the Scala channel does it, so maybe they may be able to help? AFAIK the easiest way is via https://t2bot.io/discord/ but I haven't tested it, happy to help on the Matrix side!

**Comment by gvolpe** [comment]
FWIW I've solved this on the application side by adding an "acknowledgement" mechanism to ensure the message is received, which I think it's nice regardless of the current issue, giving stronger guarantees.

Probably worth looking into the WS echo server example to compare it with `0.3.2`, but don't lose your head with it! 😄 

Happy to help with what I can :)

**Comment by davesmith00000** [comment]
Evening @gvolpe :wave: 

Mixed success. :smile: 

**Discord:**

t2bot looks easy enough, but I have no idea what I'm doing with Matrix itself. I'll try and read up more tomorrow.

**WebSockets**

So it's late, and I could be making this up at this point, but here's roughly what I think happens:

1. User fires a cmd to connect to the web socket.
2. Cmds are lazy, so it's popped on a queue.
3. When evaluated, the command creates a connection immediately, instantly fires any opening socket messages, and then returns an object containing the connection and the subs the user needs to register - _but they have NOT been registered yet_.
4. It emits another lazy, queued command saying "connected" which the user listens for.
5. The user grabs the event and saves the socket object in their model somewhere.
6. <At this point we get lucky, because the engine runs cmds then subs, if it was the other way around I think the process would do nothing until a new event went through the system :grimacing:>
7. The user takes the stored details from the model and registers the subs in the list.
8. <At this point, we might have a deadlock waiting for an event to trigger re-evaluation of this subs list... but that's speculation... and luckily some impatient tester sends a message so the subs list is evaulated.>
9. By this time any initial messages are long gone assuming a responsive server.

If I'm right, the fix is to not create/open the connection until we're also in a position to register the subs in the same pass. Somehow.

It's a theory. I'll see if I can prove it, but probably not until the weekend unfortunately...

**Comment by gvolpe** [comment]
That's a good dig, and there's absolutely no rush Dave, thanks a lot for even looking into it so quickly!

**Comment by gvolpe** [comment]
I did something quick and dirty using a mutable queue to see if things work, and yes, registering the listener immediately (no laziness) works. I didn't dive much into the runtime of `Cmd` and `Sub`, but if you think their native laziness only affects the Web Socket implementation, we could have a mutable implementation with an immutable API. 

```scala
import fs2.Stream
import scala.collection.mutable.Queue

  private def newConnection[F[_]: Async](
      address: String,
      onOpenSendMessage: Option[String],
      settings: KeepAliveSettings
  ): F[LiveSocket[F]] =
    Async[F].delay {
      val msgQueue = Queue.empty[WebSocketEvent]

      val msgListener = Functions.fun { e =>
        val event = WebSocketEvent.Receive(e.asInstanceOf[dom.MessageEvent].data.toString)
        msgQueue.enqueue(event)
      }

      val socket    = new dom.WebSocket(address)
      val keepAlive = new KeepAlive(socket, settings)

      // TODO: Probably `newConnection` needs to be a resource so we can remove the listener on clean up
      socket.addEventListener("message", msgListener)

      val subs =
        Sub.Batch(
          //Sub.fromEvent("message", socket) { e =>
          //Some(WebSocketEvent.Receive(e.asInstanceOf[dom.MessageEvent].data.toString))
          //},
          Sub.make(
            "message-queue",
            Stream.repeatEval {
              Sync[F].delay {
                try Some(msgQueue.dequeue())
                catch _ => None
              }
            }.unNone
          ),
          Sub.fromEvent("error", socket) { e =>
            val msg =
              try e.asInstanceOf[dom.ErrorEvent].message
              catch { case _: Throwable => "Unknown" }
            Some(WebSocketEvent.Error(msg))
          },
          Sub.fromEvent("close", socket) { e =>
            val ev = e.asInstanceOf[dom.CloseEvent]
            Some(WebSocketEvent.Close(ev.code, ev.reason))
          },
          Sub.fromEvent("open", socket) { _ =>
            onOpenSendMessage.foreach(msg => socket.send(msg))
            Some(WebSocketEvent.Open)
          },
          keepAlive.run
        )

      LiveSocket(socket, subs)
    }
```

**Comment by davesmith00000** [comment]
I'm catching up on Tyrian stuff having been occupied by other things for a while.

Reviewing this, I think what you've sketched out there makes a lot of sense tbh. I'll see if I can implement the `Resource` safe version. Thanks for doing that. :pray:

**Comment by gvolpe** [comment]
Cool, no worries @davesmith00000 , thanks for looking into it! 

Here's the slightly different version that made it into my app: https://github.com/gvolpe/trading/blob/main/modules/ws-client/src/main/scala/trading/client/WebSocket.scala

**Comment by davesmith00000** [comment]
Oh cool, I'll take a look!

**Comment by davesmith00000** [comment]
This will be fixed in the next release - which may be later today!
