### ISSUE TITLE
Relative Path of Index.???.js when used with a Reverse Proxy (nginx)

### ISSUE THREAD

**Issue by PsyfireX** [PurpleKingdomGames/tyrian#206]
If you use a reverse proxy like nginx to alter the path of the root, the path to the "index.js" file is broken.

nginx.conf

```
#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;


        location /ui2 {
            proxy_pass http://host.docker.internal:1234;
        }


    }


}

```
When accessing the home/index/root page, at `localhost/ui2` the browser attempts to access the index.js file under an incorrect relative path at `localhost/index.cb180e2c.js` when it should point to `localhost/ui2/index.cb180e2c.js`

index.html
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>tagr-ui</title>
</head>

<body>
  <div id="myapp"></div>
  <script src="/index.cb180e2c.js" defer=""></script>
</body>

</html>
```

**Comment by davesmith00000** [comment]
Hi!

This is good solid web stuff, not specific to Tyrian - but that's ok! I'm not an nginx person so I could be wrong, but essentially I think there's a misunderstanding about what's going on here. (I bet ChatGPT would be able to explain this better than me. :joy:)

You've set up a proxy pass so that any requests going to `/ui` will be redirected to `/` (root), but that is not what the web page is asking for, it's asking for root in the first place, like this: `src="/index.cb180e2c.js"`. If you update this to `src="/ui/index.cb180e2c.js"`, I imagine it will work.

That url is being created by your bundler, Parcel.js (I assume), so how do we change it? To get Parcel.js to use an adjusted url, you can specify the `--public-url` field in the build script, like the example below (I haven't tested this, but it should work):

```json
{
  "scripts": {
    "build": "parcel build index.html --dist-dir dist --log-level info --public-url /ui"
  },
  "devDependencies": {
    "parcel": "^2.1.0",
    "process": "^0.11.10"
  }
}
```

I suggest you have a play around with different paths/urls - I'd just do this in a browser and see what works - and then you'll know what you need to change and where. You might also want to consider relative url's instead of absolute ones (i.e. `./` vs `/`).

Note that if you have a `start` command in your `package.json` that you use during local development, and a `build` command that you use for building for production, then you may want to _not_ set `--public-url` on the start one, and just set it on the build version. Depends on how you've got your project set up. Perhaps like this:

```json
{
  "scripts": {
    "start": "parcel build index.html --dist-dir dist --log-level info"
    "build": "parcel build index.html --dist-dir public --log-level info --public-url /ui"
  },
  "devDependencies": {
    "parcel": "^2.1.0",
    "process": "^0.11.10"
  }
}
```

Hope that helps!

**Comment by AlexITC** [comment]
Like David says, the problem isn't related to tyrian, I bet this would do the trick:

```
...
        location /ui2 {
            rewrite ^/ui2/(.*) /$1 break;
            proxy_pass http://host.docker.internal:1234;
        }
...
```

In short, re-write the url to remove the `/ui2` prefix.
