### ISSUE TITLE
Request: Provide a key Attr

### ISSUE THREAD

**Issue by stevechy** [PurpleKingdomGames/tyrian#212]
Hello,

I have some dynamic elements that are added and removed quickly with CSS animations but it looks like some animations are restarting when other elements are removed.

I think what is happening is that the first div is removed in the virtual dom but then snabbdom is removing div2 applying the second div's classes to div1 instead of actually removing div1.

```
div1 = <div class="animation-1"></div>
div2 = <div class="animation-2"></div>
```

Not entirely sure but I think adding a snabbdom key attr would make this easier to track down.

I believe the change involves adding an Attr then passing it to snabbdom in Rendering?  Not sure where `Attr`s are created...

https://github.com/PurpleKingdomGames/tyrian/blob/6710104ccc7f8ed61345f062b88d222bb82576bc/tyrian/js/src/main/scala/tyrian/runtime/Rendering.scala#L52
https://github.com/buntec/scala-js-snabbdom/blob/88b874931ccf47d7eab90231b81ca83fa400df35/snabbdom/src/main/scala/snabbdom/VNodeData.scala#L49

**Comment by davesmith00000** [comment]
6 months! Yikes! Sorry @stevechy...

I've sketched out the solution here. Wondering how to test it - any ideas?

https://github.com/PurpleKingdomGames/tyrian/pull/247

**Comment by stevechy** [comment]
> 6 months! Yikes! Sorry @stevechy...
> 
> I've sketched out the solution here. Wondering how to test it - any ideas?
> 
> #247

Thank you for sketching out the solution!  To test it, I guess there should be 2 elements A, B in the vdom, then A should be removed in the vdom and B changed and the test should confirm that the A element in the DOM was removed.

One way could be to do a render then capture the elements with `document.getElementById`, then after removing A in the vdom the updated elements could be compared with the captured ones.  

Another way could be to add some properties to the DOM elements to mark which one is which?

I haven't touched my project for a bit... not sure if there's a good place to put code capture the DOM elements before they are updated?

**Comment by davesmith00000** [comment]
I had a mooch through the snabbdom tests and surfaced thinking "assuming snabbdom works, and it looks like it does, this probably just works", but curious if there was some way to gain some confidence.

Quick test then, for a model with a list of int's called `shuffle`, that gets shuffled every second, and rendered as follows:

```scala
      div(
        model.shuffle.map { i =>
          span(id := "myspan" + i.toString())("").setKey(i.toString())
        }
      )
```

Without a key:
![tyrian_without_key](https://github.com/PurpleKingdomGames/tyrian/assets/908709/10002ebd-b9fb-4c01-869a-067bc27f53ca)

With a key:
![tyrian_with_key](https://github.com/PurpleKingdomGames/tyrian/assets/908709/b9277926-9cd1-4121-9905-93854c111fc0)

Clearly the latter is doing less work, i.e. modifying fewer nodes. :tada: 

If you slow down the animation and look at what's actually happening (for anecdotal evidence), the untouched nodes are nodes that seem not to have changed position or order before something else has, example sequence where **bold** has been moved:

...
4 **1** 2 5 **3**
**1** **3** 4 2 5
2 **4** **3** 5 **1**
...

In all three lines, 2 and 5 do not change order, and they aren't the first things that need to move in order to affect the order. Between the first two lines, 4 doesn't need to move either to efficiently affect the order.
On line three 2 and 5 haven't changed order, but 4 and 3 and 1 have changed order and moved.

Are there any conclusions here? I mean.. nothing definite, but I'm inclined to merge it on the basis that:

1. The change doesn't hurt anything.
2. I'm trying to get a release out. :smile: 
3. I don't have any better ideas for testing, but if someone comes back with a new use case once the functionality is available, then we can test against it and we can revisit as necessary.

What do you think @stevechy? @hobnob?

**Comment by davesmith00000** [comment]
Thanks @hobnob, I've merged the change and I'll close this issue for now. :+1:
